name: Continuous Integration

on:
  push:
    branches: 
      - master
      
    paths-ignore:
      - '.github/**'
      - 'doc/**'

jobs:
  NuGet:
    
    runs-on: ubuntu-latest
    env:
      NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json
      NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }} 
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        source-url: ${{ env.NUGET_SOURCE_URL }}
        dotnet-version: 9.x
    
    - name: Restore dependencies (dotnet restore)
      run: dotnet restore
      working-directory: src
      
    - name: Build (dotnet build)
      run: dotnet build --configuration release --no-restore
      working-directory: src
      
    - name: Test (dotnet test)
      run: dotnet test --configuration release --no-build --verbosity normal
      working-directory: src
